---

baseURL:                  "https://the-independent-friend.de/"
languageCode:             "de-DE"
title:                    "the independent friend"
theme:                    "gohugo-theme-ananke-2.9.1"
MetaDataFormat:           "yaml"
DefaultContentLanguage:   "de"
Paginate:                 24
googleAnalytics:          ""
enableRobotsTXT:          true
featured_image:           "/images/krefeld-pistorius-denkmal.jpg"


menu:
  main:
  - identifier:           blog
    name:                 Nachrichten
    title:                Nachrichten
    url:                  /posts/
    weight:               1
  - identifier:           Krefeld
    name:                 Krefeld
    title:                Krefeld
    url:                  /page/krefeld/
    weight:               2
  - identifier:           Impressum
    name:                 Impressum
    title:                Impressum
    url:                  /page/impressum/
    weight:               3


sitemap:
  #changefreq: "yearly"
  changefreq:             "monthly"
  priority:               0.5
  filename:               "sitemap.xml"

params:
  favicon:                ""
  description:            "the independent friend"
  background_color_class: "bg-black"
  featured_image:         "/images/page-pic.jpg"
  recent_posts_number:    12
  # body_classes: "left"
  robots:
    index:                true
    follow:               true


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote:           true
    renderer:
      unsafe:             true
