---
- hosts: all
  tasks:
    - name: "ping"
      ping:

    - name: "Clean cach"
      file:
        state: absent
        path: "../public/"
      delegate_to: localhost

    - name: "run hugo"
      shell: "hugo"
      args:
        chdir: ../
      delegate_to: localhost

    - name: "sync html code"
      synchronize:
        src: ../public/
        dest: /srv/nginx/tif-static/
        delete: "yes"

    - name: "Set owner"
      file:
        dest: "/srv/nginx/tif-static/"
        owner: "root"
        group: "root"
        mode: 0755
        recurse: "yes"

    - name: "sync nginx config"
      synchronize:
        src: ./files/tif-static.conf
        dest: /etc/nginx/conf.d/tif-static.conf

    - name: "check nginx config"
      shell: "nginx -t"
      args:

    - name: "Reload nginx"
      service:
        name: nginx
        state: restarted

#  cd /opt/
#  wget https://dl.eff.org/certbot-auto
#  chmod a+x ./certbot-aut
#  ./certbot-auto certonly -a webroot --webroot-path=/var/www/tif-static/ -d the-independent-friend.de --debug-challenges -v
# ./certbot-auto certonly -a webroot --webroot-path=/srv/nginx/ -d the-independent-friend.de --debug-challenges -v
# ./certbot-auto  --nginx --webroot-path=/srv/nginx/ -d the-independent-friend.de --debug-challenges -v
# ./certbot-auto  --nginx -d the-independent-friend.de --debug-challenges -v

    # - name: "sync letsencrypt config"
    #   copy:
    #     src: ./files/renewal/the-independent-friend.de.conf
    #     dest: /etc/letsencrypt/renewal/the-independent-friend.de.conf
    #     owner: root
    #     group: root
    #     mode: 0644
        #delete: "yes"
