---
- hosts: all
  tasks:
    - name: "ping"
      ping:

    - name: "Clean cach"
      file:
        state: absent
        path: "../public/"
      delegate_to: localhost

    - name: "run hugo"
      shell: "hugo"
      args:
        chdir: ../
      delegate_to: localhost

    - name: "sync code"
      synchronize:
        src: ../public/
        dest: /var/www/tif-static/
        delete: "yes"

    - name: "sync nginx config"
      synchronize:
        src: ./tif-static.conf
        dest: /etc/nginx/conf.d/tif-static.conf

    - name: "Reload nginx"
      service:
        name: nginx
        state: reloaded
