---
- hosts: all
  tasks:
    - name: "ping"
      ping:

    - name: "dry-run certbot-auto"
      shell: "./certbot-auto renew --dry-run"
      args:
        chdir: "/opt/"

    - name: "run certbot-auto"
      shell: "./certbot-auto certonly --nginx --email briefkasten@olaf-radicke.de --agree-tos -d the-independent-friend.de,olaf-radicke.de"
      args:
        chdir: "/opt/"

    - name: "check nginx config"
      shell: "nginx -t"
      args:
        chdir: "/opt/"

    - name: "Reload nginx"
      service:
        name: nginx
        state: reloaded
